// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: guild.proto

package server

import (
	"context"

	"chatskn/app/guild/rpc/internal/logic"
	"chatskn/app/guild/rpc/internal/svc"
	"chatskn/app/guild/rpc/pb"
)

type GuildServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGuildServer
}

func NewGuildServer(svcCtx *svc.ServiceContext) *GuildServer {
	return &GuildServer{
		svcCtx: svcCtx,
	}
}

func (s *GuildServer) Create(ctx context.Context, in *pb.CreateReq) (*pb.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *GuildServer) CreateChannel(ctx context.Context, in *pb.CreateChannelReq) (*pb.CreateChannelResp, error) {
	l := logic.NewCreateChannelLogic(ctx, s.svcCtx)
	return l.CreateChannel(in)
}

// rpc get() returns();
func (s *GuildServer) GetChannelMembers(ctx context.Context, in *pb.GetChannelMembersReq) (*pb.GetChannelMembersResp, error) {
	l := logic.NewGetChannelMembersLogic(ctx, s.svcCtx)
	return l.GetChannelMembers(in)
}
