// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: guild.proto

package guild

import (
	"context"

	"chatskn/app/guild/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChannelMember         = pb.ChannelMember
	CreateChannelReq      = pb.CreateChannelReq
	CreateChannelResp     = pb.CreateChannelResp
	CreateReq             = pb.CreateReq
	CreateResp            = pb.CreateResp
	GetChannelMembersReq  = pb.GetChannelMembersReq
	GetChannelMembersResp = pb.GetChannelMembersResp
	Guild                 = pb.Guild

	GuildZrpcClient interface {
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		CreateChannel(ctx context.Context, in *CreateChannelReq, opts ...grpc.CallOption) (*CreateChannelResp, error)
		// rpc get() returns();
		GetChannelMembers(ctx context.Context, in *GetChannelMembersReq, opts ...grpc.CallOption) (*GetChannelMembersResp, error)
	}

	defaultGuildZrpcClient struct {
		cli zrpc.Client
	}
)

func NewGuildZrpcClient(cli zrpc.Client) GuildZrpcClient {
	return &defaultGuildZrpcClient{
		cli: cli,
	}
}

func (m *defaultGuildZrpcClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := pb.NewGuildClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultGuildZrpcClient) CreateChannel(ctx context.Context, in *CreateChannelReq, opts ...grpc.CallOption) (*CreateChannelResp, error) {
	client := pb.NewGuildClient(m.cli.Conn())
	return client.CreateChannel(ctx, in, opts...)
}

// rpc get() returns();
func (m *defaultGuildZrpcClient) GetChannelMembers(ctx context.Context, in *GetChannelMembersReq, opts ...grpc.CallOption) (*GetChannelMembersResp, error) {
	client := pb.NewGuildClient(m.cli.Conn())
	return client.GetChannelMembers(ctx, in, opts...)
}
