// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: message.proto

package server

import (
	"context"

	"chatskn/app/message/rpc/internal/logic"
	"chatskn/app/message/rpc/internal/svc"
	"chatskn/app/message/rpc/pb"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Storage(ctx context.Context, in *pb.StorageReq) (*pb.StorageResp, error) {
	l := logic.NewStorageLogic(ctx, s.svcCtx)
	return l.Storage(in)
}
