// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelFieldNames          = builder.RawFieldNames(&Channel{})
	channelRows                = strings.Join(channelFieldNames, ",")
	channelRowsExpectAutoSet   = strings.Join(stringx.Remove(channelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelRowsWithPlaceHolder = strings.Join(stringx.Remove(channelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	chatSknCacheChannelIdPrefix = "chatSknCache:channel:id:"
)

type (
	channelModel interface {
		Insert(ctx context.Context, data *Channel) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, data *Channel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Channel, error)
		Update(ctx context.Context, data *Channel) error
		UpdateWithSession(ctx context.Context, session sqlx.Session, data *Channel) error
		Delete(ctx context.Context, id int64) error
		DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultChannelModel struct {
		sqlc.CachedConn
		table string
	}

	Channel struct {
		Id       int64     `db:"id"`
		GuildId  int64     `db:"guild_id"`
		Name     string    `db:"name"`
		CreateAt time.Time `db:"create_at"`
	}
)

func newChannelModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultChannelModel {
	return &defaultChannelModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`channel`",
	}
}

func (m *defaultChannelModel) Delete(ctx context.Context, id int64) error {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, channelIdKey)
	return err
}

func (m *defaultChannelModel) DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, id)
	}, channelIdKey)
	return err
}

func (m *defaultChannelModel) FindOne(ctx context.Context, id int64) (*Channel, error) {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, id)
	var resp Channel
	err := m.QueryRowCtx(ctx, &resp, channelIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelModel) Insert(ctx context.Context, data *Channel) (sql.Result, error) {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, channelRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GuildId, data.Name)
	}, channelIdKey)
	return ret, err
}

func (m *defaultChannelModel) InsertWithSession(ctx context.Context, session sqlx.Session, data *Channel) (sql.Result, error) {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, channelRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.GuildId, data.Name)
	}, channelIdKey)
	return ret, err
}

func (m *defaultChannelModel) Update(ctx context.Context, data *Channel) error {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.GuildId, data.Name, data.Id)
	}, channelIdKey)
	return err
}

func (m *defaultChannelModel) UpdateWithSession(ctx context.Context, session sqlx.Session, data *Channel) error {
	channelIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.GuildId, data.Name, data.Id)
	}, channelIdKey)
	return err
}

func (m *defaultChannelModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", chatSknCacheChannelIdPrefix, primary)
}

func (m *defaultChannelModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChannelModel) tableName() string {
	return m.table
}
