// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelMemberFieldNames          = builder.RawFieldNames(&ChannelMember{})
	channelMemberRows                = strings.Join(channelMemberFieldNames, ",")
	channelMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(channelMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelMemberRowsWithPlaceHolder = strings.Join(stringx.Remove(channelMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	chatSknCacheChannelMemberIdPrefix = "chatSknCache:channelMember:id:"
)

type (
	channelMemberModel interface {
		Insert(ctx context.Context, data *ChannelMember) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, data *ChannelMember) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChannelMember, error)
		Update(ctx context.Context, data *ChannelMember) error
		UpdateWithSession(ctx context.Context, session sqlx.Session, data *ChannelMember) error
		Delete(ctx context.Context, id int64) error
		DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultChannelMemberModel struct {
		sqlc.CachedConn
		table string
	}

	ChannelMember struct {
		Id        int64     `db:"id"`
		ChannelId int64     `db:"channel_id"`
		UserId    int64     `db:"user_id"`
		Role      int64     `db:"role"` // 1: member普通成员;2: 管理员;3: owner拥有者;4: admin系统管理员
		CreateAt  time.Time `db:"create_at"`
	}
)

func newChannelMemberModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultChannelMemberModel {
	return &defaultChannelMemberModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`channelMember`",
	}
}

func (m *defaultChannelMemberModel) Delete(ctx context.Context, id int64) error {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, channelMemberIdKey)
	return err
}

func (m *defaultChannelMemberModel) DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, id)
	}, channelMemberIdKey)
	return err
}

func (m *defaultChannelMemberModel) FindOne(ctx context.Context, id int64) (*ChannelMember, error) {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, id)
	var resp ChannelMember
	err := m.QueryRowCtx(ctx, &resp, channelMemberIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelMemberRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelMemberModel) Insert(ctx context.Context, data *ChannelMember) (sql.Result, error) {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, channelMemberRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ChannelId, data.UserId, data.Role)
	}, channelMemberIdKey)
	return ret, err
}

func (m *defaultChannelMemberModel) InsertWithSession(ctx context.Context, session sqlx.Session, data *ChannelMember) (sql.Result, error) {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, channelMemberRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.ChannelId, data.UserId, data.Role)
	}, channelMemberIdKey)
	return ret, err
}

func (m *defaultChannelMemberModel) Update(ctx context.Context, data *ChannelMember) error {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelMemberRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ChannelId, data.UserId, data.Role, data.Id)
	}, channelMemberIdKey)
	return err
}

func (m *defaultChannelMemberModel) UpdateWithSession(ctx context.Context, session sqlx.Session, data *ChannelMember) error {
	channelMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelMemberRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.ChannelId, data.UserId, data.Role, data.Id)
	}, channelMemberIdKey)
	return err
}

func (m *defaultChannelMemberModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", chatSknCacheChannelMemberIdPrefix, primary)
}

func (m *defaultChannelMemberModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelMemberRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChannelMemberModel) tableName() string {
	return m.table
}
