// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	guildFieldNames          = builder.RawFieldNames(&Guild{})
	guildRows                = strings.Join(guildFieldNames, ",")
	guildRowsExpectAutoSet   = strings.Join(stringx.Remove(guildFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	guildRowsWithPlaceHolder = strings.Join(stringx.Remove(guildFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	chatSknCacheGuildIdPrefix = "chatSknCache:guild:id:"
)

type (
	guildModel interface {
		Insert(ctx context.Context, data *Guild) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, data *Guild) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Guild, error)
		Update(ctx context.Context, data *Guild) error
		UpdateWithSession(ctx context.Context, session sqlx.Session, data *Guild) error
		Delete(ctx context.Context, id int64) error
		DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultGuildModel struct {
		sqlc.CachedConn
		table string
	}

	Guild struct {
		Id       int64     `db:"id"`
		OwnerId  int64     `db:"owner_id"`
		Name     string    `db:"name"`
		CreateAt time.Time `db:"create_at"`
	}
)

func newGuildModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGuildModel {
	return &defaultGuildModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`guild`",
	}
}

func (m *defaultGuildModel) Delete(ctx context.Context, id int64) error {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, guildIdKey)
	return err
}

func (m *defaultGuildModel) DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, id)
	}, guildIdKey)
	return err
}

func (m *defaultGuildModel) FindOne(ctx context.Context, id int64) (*Guild, error) {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, id)
	var resp Guild
	err := m.QueryRowCtx(ctx, &resp, guildIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", guildRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGuildModel) Insert(ctx context.Context, data *Guild) (sql.Result, error) {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, guildRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OwnerId, data.Name)
	}, guildIdKey)
	return ret, err
}

func (m *defaultGuildModel) InsertWithSession(ctx context.Context, session sqlx.Session, data *Guild) (sql.Result, error) {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, guildRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.OwnerId, data.Name)
	}, guildIdKey)
	return ret, err
}

func (m *defaultGuildModel) Update(ctx context.Context, data *Guild) error {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, guildRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OwnerId, data.Name, data.Id)
	}, guildIdKey)
	return err
}

func (m *defaultGuildModel) UpdateWithSession(ctx context.Context, session sqlx.Session, data *Guild) error {
	guildIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, guildRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.OwnerId, data.Name, data.Id)
	}, guildIdKey)
	return err
}

func (m *defaultGuildModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", chatSknCacheGuildIdPrefix, primary)
}

func (m *defaultGuildModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", guildRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGuildModel) tableName() string {
	return m.table
}
