// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	guildMemberFieldNames          = builder.RawFieldNames(&GuildMember{})
	guildMemberRows                = strings.Join(guildMemberFieldNames, ",")
	guildMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(guildMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	guildMemberRowsWithPlaceHolder = strings.Join(stringx.Remove(guildMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	chatSknCacheGuildMemberIdPrefix = "chatSknCache:guildMember:id:"
)

type (
	guildMemberModel interface {
		Insert(ctx context.Context, data *GuildMember) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, data *GuildMember) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GuildMember, error)
		Update(ctx context.Context, data *GuildMember) error
		UpdateWithSession(ctx context.Context, session sqlx.Session, data *GuildMember) error
		Delete(ctx context.Context, id int64) error
		DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultGuildMemberModel struct {
		sqlc.CachedConn
		table string
	}

	GuildMember struct {
		Id       int64     `db:"id"`
		GuildId  int64     `db:"guild_id"`
		UserId   int64     `db:"user_id"`
		Role     int64     `db:"role"` // 1: member普通成员;2: 管理员;3: owner拥有者;4: admin系统管理员
		CreateAt time.Time `db:"create_at"`
	}
)

func newGuildMemberModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGuildMemberModel {
	return &defaultGuildMemberModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`guildMember`",
	}
}

func (m *defaultGuildMemberModel) Delete(ctx context.Context, id int64) error {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, guildMemberIdKey)
	return err
}

func (m *defaultGuildMemberModel) DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, id)
	}, guildMemberIdKey)
	return err
}

func (m *defaultGuildMemberModel) FindOne(ctx context.Context, id int64) (*GuildMember, error) {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, id)
	var resp GuildMember
	err := m.QueryRowCtx(ctx, &resp, guildMemberIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", guildMemberRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGuildMemberModel) Insert(ctx context.Context, data *GuildMember) (sql.Result, error) {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, guildMemberRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GuildId, data.UserId, data.Role)
	}, guildMemberIdKey)
	return ret, err
}

func (m *defaultGuildMemberModel) InsertWithSession(ctx context.Context, session sqlx.Session, data *GuildMember) (sql.Result, error) {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, guildMemberRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.GuildId, data.UserId, data.Role)
	}, guildMemberIdKey)
	return ret, err
}

func (m *defaultGuildMemberModel) Update(ctx context.Context, data *GuildMember) error {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, guildMemberRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.GuildId, data.UserId, data.Role, data.Id)
	}, guildMemberIdKey)
	return err
}

func (m *defaultGuildMemberModel) UpdateWithSession(ctx context.Context, session sqlx.Session, data *GuildMember) error {
	guildMemberIdKey := fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, guildMemberRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.GuildId, data.UserId, data.Role, data.Id)
	}, guildMemberIdKey)
	return err
}

func (m *defaultGuildMemberModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", chatSknCacheGuildMemberIdPrefix, primary)
}

func (m *defaultGuildMemberModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", guildMemberRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGuildMemberModel) tableName() string {
	return m.table
}
