// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: guild.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Guild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guild) Reset() {
	*x = Guild{}
	mi := &file_guild_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guild) ProtoMessage() {}

func (x *Guild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guild.ProtoReflect.Descriptor instead.
func (*Guild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

func (x *Guild) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Guild) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Guild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChannelMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ChannelId     int64                  `protobuf:"varint,2,opt,name=channelId,proto3" json:"channelId"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId"`
	Role          int64                  `protobuf:"varint,4,opt,name=role,proto3" json:"role"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMember) Reset() {
	*x = ChannelMember{}
	mi := &file_guild_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMember) ProtoMessage() {}

func (x *ChannelMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMember.ProtoReflect.Descriptor instead.
func (*ChannelMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelMember) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChannelMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChannelMember) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_guild_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReq) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_guild_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       int64                  `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId"`
	Name          int64                  `protobuf:"varint,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelReq) Reset() {
	*x = CreateChannelReq{}
	mi := &file_guild_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelReq) ProtoMessage() {}

func (x *CreateChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelReq.ProtoReflect.Descriptor instead.
func (*CreateChannelReq) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChannelReq) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *CreateChannelReq) GetName() int64 {
	if x != nil {
		return x.Name
	}
	return 0
}

type CreateChannelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResp) Reset() {
	*x = CreateChannelResp{}
	mi := &file_guild_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResp) ProtoMessage() {}

func (x *CreateChannelResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResp.ProtoReflect.Descriptor instead.
func (*CreateChannelResp) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{5}
}

func (x *CreateChannelResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetChannelMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelMembersReq) Reset() {
	*x = GetChannelMembersReq{}
	mi := &file_guild_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelMembersReq) ProtoMessage() {}

func (x *GetChannelMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelMembersReq.ProtoReflect.Descriptor instead.
func (*GetChannelMembersReq) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{6}
}

func (x *GetChannelMembersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetChannelMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MembersInfo   []*ChannelMember       `protobuf:"bytes,1,rep,name=membersInfo,proto3" json:"membersInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelMembersResp) Reset() {
	*x = GetChannelMembersResp{}
	mi := &file_guild_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelMembersResp) ProtoMessage() {}

func (x *GetChannelMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelMembersResp.ProtoReflect.Descriptor instead.
func (*GetChannelMembersResp) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{7}
}

func (x *GetChannelMembersResp) GetMembersInfo() []*ChannelMember {
	if x != nil {
		return x.MembersInfo
	}
	return nil
}

var File_guild_proto protoreflect.FileDescriptor

const file_guild_proto_rawDesc = "" +
	"\n" +
	"\vguild.proto\x12\x02pb\"E\n" +
	"\x05Guild\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"i\n" +
	"\rChannelMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tchannelId\x18\x02 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x03R\x04role\"9\n" +
	"\tCreateReq\x12\x18\n" +
	"\aownerId\x18\x01 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1c\n" +
	"\n" +
	"CreateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x10CreateChannelReq\x12\x18\n" +
	"\aguildId\x18\x01 \x01(\x03R\aguildId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\x03R\x04name\"#\n" +
	"\x11CreateChannelResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\x14GetChannelMembersReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x15GetChannelMembersResp\x123\n" +
	"\vmembersInfo\x18\x01 \x03(\v2\x11.pb.ChannelMemberR\vmembersInfo2\xb8\x01\n" +
	"\x05guild\x12'\n" +
	"\x06create\x12\r.pb.CreateReq\x1a\x0e.pb.CreateResp\x12<\n" +
	"\rcreateChannel\x12\x14.pb.CreateChannelReq\x1a\x15.pb.CreateChannelResp\x12H\n" +
	"\x11getChannelMembers\x12\x18.pb.GetChannelMembersReq\x1a\x19.pb.GetChannelMembersRespB\x06Z\x04./pbb\x06proto3"

var (
	file_guild_proto_rawDescOnce sync.Once
	file_guild_proto_rawDescData []byte
)

func file_guild_proto_rawDescGZIP() []byte {
	file_guild_proto_rawDescOnce.Do(func() {
		file_guild_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_proto_rawDesc), len(file_guild_proto_rawDesc)))
	})
	return file_guild_proto_rawDescData
}

var file_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_guild_proto_goTypes = []any{
	(*Guild)(nil),                 // 0: pb.Guild
	(*ChannelMember)(nil),         // 1: pb.ChannelMember
	(*CreateReq)(nil),             // 2: pb.CreateReq
	(*CreateResp)(nil),            // 3: pb.CreateResp
	(*CreateChannelReq)(nil),      // 4: pb.CreateChannelReq
	(*CreateChannelResp)(nil),     // 5: pb.CreateChannelResp
	(*GetChannelMembersReq)(nil),  // 6: pb.GetChannelMembersReq
	(*GetChannelMembersResp)(nil), // 7: pb.GetChannelMembersResp
}
var file_guild_proto_depIdxs = []int32{
	1, // 0: pb.GetChannelMembersResp.membersInfo:type_name -> pb.ChannelMember
	2, // 1: pb.guild.create:input_type -> pb.CreateReq
	4, // 2: pb.guild.createChannel:input_type -> pb.CreateChannelReq
	6, // 3: pb.guild.getChannelMembers:input_type -> pb.GetChannelMembersReq
	3, // 4: pb.guild.create:output_type -> pb.CreateResp
	5, // 5: pb.guild.createChannel:output_type -> pb.CreateChannelResp
	7, // 6: pb.guild.getChannelMembers:output_type -> pb.GetChannelMembersResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_guild_proto_init() }
func file_guild_proto_init() {
	if File_guild_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_proto_rawDesc), len(file_guild_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guild_proto_goTypes,
		DependencyIndexes: file_guild_proto_depIdxs,
		MessageInfos:      file_guild_proto_msgTypes,
	}.Build()
	File_guild_proto = out.File
	file_guild_proto_goTypes = nil
	file_guild_proto_depIdxs = nil
}
