// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: guild.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Guild_Create_FullMethodName            = "/pb.guild/create"
	Guild_CreateChannel_FullMethodName     = "/pb.guild/createChannel"
	Guild_GetChannelMembers_FullMethodName = "/pb.guild/getChannelMembers"
)

// GuildClient is the client API for Guild service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -- service --
type GuildClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
	CreateChannel(ctx context.Context, in *CreateChannelReq, opts ...grpc.CallOption) (*CreateChannelResp, error)
	//	rpc get() returns();
	//	rpc delete() returns();
	//	rpc createChannel() returns():
	//	rpc inviteUser() returns();
	//
	// channel
	GetChannelMembers(ctx context.Context, in *GetChannelMembersReq, opts ...grpc.CallOption) (*GetChannelMembersResp, error)
}

type guildClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildClient(cc grpc.ClientConnInterface) GuildClient {
	return &guildClient{cc}
}

func (c *guildClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, Guild_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) CreateChannel(ctx context.Context, in *CreateChannelReq, opts ...grpc.CallOption) (*CreateChannelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChannelResp)
	err := c.cc.Invoke(ctx, Guild_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) GetChannelMembers(ctx context.Context, in *GetChannelMembersReq, opts ...grpc.CallOption) (*GetChannelMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChannelMembersResp)
	err := c.cc.Invoke(ctx, Guild_GetChannelMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildServer is the server API for Guild service.
// All implementations must embed UnimplementedGuildServer
// for forward compatibility.
//
// -- service --
type GuildServer interface {
	Create(context.Context, *CreateReq) (*CreateResp, error)
	CreateChannel(context.Context, *CreateChannelReq) (*CreateChannelResp, error)
	//	rpc get() returns();
	//	rpc delete() returns();
	//	rpc createChannel() returns():
	//	rpc inviteUser() returns();
	//
	// channel
	GetChannelMembers(context.Context, *GetChannelMembersReq) (*GetChannelMembersResp, error)
	mustEmbedUnimplementedGuildServer()
}

// UnimplementedGuildServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildServer struct{}

func (UnimplementedGuildServer) Create(context.Context, *CreateReq) (*CreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGuildServer) CreateChannel(context.Context, *CreateChannelReq) (*CreateChannelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedGuildServer) GetChannelMembers(context.Context, *GetChannelMembersReq) (*GetChannelMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannelMembers not implemented")
}
func (UnimplementedGuildServer) mustEmbedUnimplementedGuildServer() {}
func (UnimplementedGuildServer) testEmbeddedByValue()               {}

// UnsafeGuildServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildServer will
// result in compilation errors.
type UnsafeGuildServer interface {
	mustEmbedUnimplementedGuildServer()
}

func RegisterGuildServer(s grpc.ServiceRegistrar, srv GuildServer) {
	// If the following call pancis, it indicates UnimplementedGuildServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Guild_ServiceDesc, srv)
}

func _Guild_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).CreateChannel(ctx, req.(*CreateChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_GetChannelMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).GetChannelMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_GetChannelMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).GetChannelMembers(ctx, req.(*GetChannelMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Guild_ServiceDesc is the grpc.ServiceDesc for Guild service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Guild_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.guild",
	HandlerType: (*GuildServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _Guild_Create_Handler,
		},
		{
			MethodName: "createChannel",
			Handler:    _Guild_CreateChannel_Handler,
		},
		{
			MethodName: "getChannelMembers",
			Handler:    _Guild_GetChannelMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guild.proto",
}
