// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{})
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageRowsWithPlaceHolder = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	chatSknCacheMessageIdPrefix = "chatSknCache:message:id:"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, data *Message) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Message, error)
		Update(ctx context.Context, data *Message) error
		UpdateWithSession(ctx context.Context, session sqlx.Session, data *Message) error
		Delete(ctx context.Context, id int64) error
		DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultMessageModel struct {
		sqlc.CachedConn
		table string
	}

	Message struct {
		Id         int64     `db:"id"`
		SenderId   int64     `db:"sender_id"`
		ReceiverId int64     `db:"receiver_id"` // 私聊功能时使用,其他时刻为0
		ChannelId  int64     `db:"channel_id"`  // 私聊功能时为0
		Type       string    `db:"type"`        // text、image、file,为image、file时content为存储路径
		Content    string    `db:"content"`
		CreateAt   time.Time `db:"create_at"`
	}
)

func newMessageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageModel {
	return &defaultMessageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`message`",
	}
}

func (m *defaultMessageModel) Delete(ctx context.Context, id int64) error {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, messageIdKey)
	return err
}

func (m *defaultMessageModel) DeleteWithSession(ctx context.Context, session sqlx.Session, id int64) error {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, id)
	}, messageIdKey)
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, id int64) (*Message, error) {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, id)
	var resp Message
	err := m.QueryRowCtx(ctx, &resp, messageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message) (sql.Result, error) {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, messageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.ChannelId, data.Type, data.Content)
	}, messageIdKey)
	return ret, err
}

func (m *defaultMessageModel) InsertWithSession(ctx context.Context, session sqlx.Session, data *Message) (sql.Result, error) {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, messageRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.ChannelId, data.Type, data.Content)
	}, messageIdKey)
	return ret, err
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message) error {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.ChannelId, data.Type, data.Content, data.Id)
	}, messageIdKey)
	return err
}

func (m *defaultMessageModel) UpdateWithSession(ctx context.Context, session sqlx.Session, data *Message) error {
	messageIdKey := fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.ChannelId, data.Type, data.Content, data.Id)
	}, messageIdKey)
	return err
}

func (m *defaultMessageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", chatSknCacheMessageIdPrefix, primary)
}

func (m *defaultMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
