// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	ws "chatskn/app/ws/rpc/internal/handler/ws"
	"chatskn/app/ws/rpc/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// connect
				Method:  http.MethodGet,
				Path:    "/connect/:id",
				Handler: ws.ConnectWsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ws"),
	)
}
