// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: message.proto

package message

import (
	"context"

	"chatskn/app/message/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Message     = pb.Message
	StorageReq  = pb.StorageReq
	StorageResp = pb.StorageResp

	MessageZrpcClient interface {
		Storage(ctx context.Context, in *StorageReq, opts ...grpc.CallOption) (*StorageResp, error)
	}

	defaultMessageZrpcClient struct {
		cli zrpc.Client
	}
)

func NewMessageZrpcClient(cli zrpc.Client) MessageZrpcClient {
	return &defaultMessageZrpcClient{
		cli: cli,
	}
}

func (m *defaultMessageZrpcClient) Storage(ctx context.Context, in *StorageReq, opts ...grpc.CallOption) (*StorageResp, error) {
	client := pb.NewMessageClient(m.cli.Conn())
	return client.Storage(ctx, in, opts...)
}
