// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: email.proto

package server

import (
	"context"
	"email/rpc/internal/logic"
	"email/rpc/internal/svc"
	pb2 "email/rpc/pb"
)

type EmailServer struct {
	svcCtx *svc.ServiceContext
	pb2.UnimplementedEmailServer
}

func NewEmailServer(svcCtx *svc.ServiceContext) *EmailServer {
	return &EmailServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServer) Send(ctx context.Context, in *pb2.SendReq) (*pb2.SendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}
